### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by minowu** [VitualReaty/vue-human#1]
🚀  in progress / 👍 next work

---

### Bases

- [x] [Color](https://developer.apple.com/ios/human-interface-guidelines/visual-design/color/)
- [x] Typography

### Grids

- [x] media query size
- [x] flex
- [x] section
- [x] spacing

### Components

- [x] [icon](10)
- [x] [button](2)
- [x] [card](4)
- [x] [form](3) 
- [x] [scroll](5)
- [x] [image](8) (!important, to handle media query image and lazyload)
- [ ] [bars](7)
- [ ] [loading](9)
